# Generated by Django 4.1.13 on 2024-02-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urlname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('state', models.BooleanField()),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schudele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
                ('frecuencyHour', models.TimeField()),
                ('Periodicity', models.TimeField()),
                ('Network', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.network')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='Schudele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.schudele'),
        ),
    ]
