# Generated by Django 4.1.13 on 2024-02-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='project.user'),
            preserve_default=False,
        ),
    ]
