# Generated by Django 4.1.13 on 2024-02-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schudele',
            name='Network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.network'),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
