# Generated by Django 4.1.13 on 2024-03-20 00:28

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_schudele_network_alter_schudele_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='network',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='Periodicity',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='endHour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='frecuencyHour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='startHour',
            field=models.DateTimeField(),
        ),
    ]
