# Generated by Django 4.1.13 on 2024-03-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_account_id_alter_data_id_alter_network_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='Periodicity',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='endHour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='frecuencyHour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schudele',
            name='startHour',
            field=models.TimeField(),
        ),
    ]
